### ISSUE TITLE
前后端本地启动，空指针

### ISSUE THREAD

**Issue by lindadev77** [zongzibinbin/MallChat#1]
![image](https://github.com/zongzibinbin/MallChat/assets/9762702/c9571fd2-8cbd-4263-9c2d-588aba9b8bec)

|ERROR|2023-05-22 23:35:46.587|http-nio-8080-exec-3|a3e6ce8f-a814-43da-aa15-f9f4cf16ba1f|uid=10818|null point exception！The reason is:null|
java.lang.NullPointerException: null
	at com.abin.mallchat.custom.user.service.adapter.UserAdapter.lambda$buildBadgeResp$0(UserAdapter.java:62)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.abin.mallchat.custom.user.service.adapter.UserAdapter.buildBadgeResp(UserAdapter.java:66)
	at com.abin.mallchat.custom.user.service.impl.UserServiceImpl.badges(UserServiceImpl.java:89)
	at com.abin.mallchat.custom.user.service.impl.UserServiceImpl$$FastClassBySpringCGLIB$$c76aabc2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)

**Comment by zongzibinbin** [comment]
入参是怎么样的，我没有复现诶

**Comment by RealBeBetter** [comment]
> 入参是怎么样的，我没有复现诶

针对这个问题提了个 PR，望考虑下。

**Comment by zongzibinbin** [comment]
欢迎pr，代码我重新格式化了，不建议pr提交格式化的部分，范围太大，容易忽略核心改动点，建议重新拉取后提交

**Comment by RealBeBetter** [comment]
> 欢迎pr，代码我重新格式化了，不建议pr提交格式化的部分，范围太大，容易忽略核心改动点，建议重新拉取后提交

已重新 PR，解决了 issue，未修改其他部分。

**Comment by lindadev77** [comment]
这个项目上周拉的分支就跑通没复现这个问题了

**Comment by lindadev77** [comment]
fixed
